### ISSUE TITLE
show media panels crashes banshee

### ISSUE THREAD

**Issue by nicman23** [arfbtwn/banshee#27]
on the new interface banshee icon -> view -> media panel, results in a crash with a segfault.

**Comment by njlittle** [comment]
Haha, I was thinking of logging that, same for mini-mode unfortunately

**Comment by arfbtwn** [comment]
Could you try the feature/fixes branch for me?

I did the change on feature/lite but cherry-picked it back as I was able to reproduce on feature/fixes as well so I'll rebase feature/lite on to there if this works okay.

The patch might need some work if you want to take a look: https://github.com/arfbtwn/banshee/pull/14/commits/3f767698cb6e775663e038685ab556fe542f2d78

**Comment by nicman23** [comment]
seems to work fine, will test it more and report in a day or two.

except the media panel, what other things you wnt feedback on?

**Comment by arfbtwn** [comment]
I also tested this patch with Mini-Mode that had the same problem and it resolved in both cases. Not sure if there's anywhere else we use the `SourceRowRenderer` but I didn't go looking.

Cheers for testing, it's appreciated, I'll give the patch a once over on the weekend and close this one off when I do.

**Comment by arfbtwn** [comment]
Should be resolved in master now ^^
