### ISSUE TITLE
banshee not accessing flacs' images 

### ISSUE THREAD

**Issue by nicman23** [arfbtwn/banshee#28]
all my library has built in each flac file the coresponding image of the album art ut banshee seems to just redownload it and thus misses a few

**Comment by arfbtwn** [comment]
yeah it should be able to read the image stored in the tag and shouldn't try to download it in that case, are you able to do any debugging to find out what's going on when Banshee tries to read the tag?

**Comment by nicman23** [comment]
does not seem to be a problem any more
