### ISSUE TITLE
B.WebBrowser: Zooming with GDK_SCROLL_SMOOTH broken

### ISSUE THREAD

**Issue by Carbenium** [arfbtwn/banshee#37]
Pressing `Ctrl` and scrolling results only in zoom out events. Relevant code: https://github.com/arfbtwn/banshee/blob/f9fb010643ed17a70244af654c2e95c586b84dfe/src/Core/Banshee.WebBrowser/Banshee.WebSource/WebView.cs#L69

The problem is caused by recent Gtk libs sending scoll events with `GDK_SCROLL_SMOOTH` instead of `_UP/_DOWN`. Normally this would be fine since the `deltaY` value of the event would specify the direction. In our case `gtk-sharp` unfortunatly just doesn't expose this field, so there is just no sane way to handle smooth scrolling.

As far as I undestand the Gtk code, there isn't a way to disable smooth scrolling on a per-widget base.

**Proposal**: Until we find a way to upgrade to a newer `gtk-sharp` lib (e.g https://github.com/openmedicus/gtk-sharp) remove the scroll handling and add zoom button to the navigation bar.

**Comment by arfbtwn** [comment]
ahh, I see - it's GDK in this case, I guess we need to find a way to call [this function][1], if we're lucky there'll be a handle we can use to get at the native event structure 🤞 

[1]: https://developer.gnome.org/gdk3/stable/gdk3-Events.html#gdk-event-get-scroll-deltas

**Comment by Carbenium** [comment]
Genius :+1: 

I updated #38 accordingly.

**Comment by arfbtwn** [comment]
Should be resolved in master after merge of #65, thanks again
