### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by jlanzarotta** [arfbtwn/banshee#46]
Hello,

Just came across banshee.  So far it looks pretty good.  Is is still being developed?  The reason I ask is that it has been quite a long time since it was released?

Thanks,

**Comment by arfbtwn** [comment]
The length of time since last release is one of the reasons for this repository (and the other forks that exist in GitHub) and yes I'm doing my best to apply bug fixes and update it for current GNOME releases so feel free to raise issues and submit patches.

**Comment by jlanzarotta** [comment]
Fantastic.  Glad the project is still going.  I am attempting to build on Windows... :)

**Comment by arfbtwn** [comment]
Cool! - we generally only build on Linux so if you're able to raise any issues or supply patches for the Windows build that would be really great :+1:
